### ISSUE TITLE
Сообщения об ошибках

### ISSUE THREAD

**Issue by paulin-mipt** [AFakeman/tictacbot#3]
Пока сообщения об ошибках не очень специфицированы. По крайней мере, стоит для каждой команды ещё раз написать "как для не очень умных пользователей", какие аргументы там ожидаются. То есть, то, что нельзя понять из help, должно быть понятно хотя бы здесь.

Ещё, так как это развлекательный бот, ему лучше бы не вести себя как консольной программе, общающейся исключительно через терминал с разработчиком. Стоит быть дружелюбнее к пользователю. 
Сообщение "Invalid field size", скажем, заменяется на что-то вроде "Try other arguments, field size should be integer in range ..." (и ещё вопрос, нужны ли нам поля меньше, чем 3x3?)

**Comment by AFakeman** [comment]
Исправлено (2a14bfd)
